# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/game/**'
      - 'packages/web/**'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/game/**'
      - 'packages/web/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install -g yarn

    - run: cd ./packages/web && yarn
    - run: |
        rm -f ./packages/web/.env &&
        touch ./packages/web/.env
        echo REACT_APP_SERVER_IP=${{ secrets.SERVER_IP }} >> ./packages/web/.env

    - run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        cd ./packages/web && yarn run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
